[project]
name = "tvdatafeed"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "setuptools>=49.2.0",
    "pandas>=1.0.5",
    "websocket-client>=0.57.0",
    "pyotp>=2.9.0",
    "python-dotenv>=1.1.1",
    "requests"
]
